apiVersion: v1
kind: Secret
metadata:
  name: secrets
type: Opaque
data:
  POSTGRES_USER: cG9zdGdyZXM=
  POSTGRES_PASSWORD: cm9vdA==
  POSTGRES_DB: dGlueXRlbXA=
  DB_URL: cG9zdGdyZXM6Ly9wb3N0Z3Jlczpyb290QHBvc3RncmVzOjU0MzIvdGlueXRlbXA=
  API_URL: aHR0cDovL3NjaGVkdWxlcjo4MDAw