apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
spec:
  replicas: 5
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
        - name: worker
          image: worker:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: API_URL
              value: "http://scheduler:8000"
            - name: WORKER_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
